function [stats_enc, stats_rec, stats_evr] = run_salience_dgii()
% RUN_SALIENCE_DGII computes performance of DeepGaze II at predicting fixated
% regions and compares to a center-bias model generated by leave-one-
% image-out cross-validation
%
% INPUTS:  none, loads relevant data from disk
%
% OUTPUTS: stats_enc - structure, stats comparing performance between
%                      models at study
%          
%          stats_rec - structure, stats comparing performance between
%                      models at test
%
%          stats_evr - structure, stats comparing performance between
%                      study and test

% Copyright (C) 2021  James Kragel

% This program is free software: you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with this program.  If not, see <https://www.gnu.org/licenses/>.

subjects =  {'S1','S2','S3','S4','S5','S6'};

for s = 1:length(subjects)
    
    [auc_enc, auc_rec, auc_center_enc, auc_center_rec] = compute_model_performance(subjects{s});
    ae(s) = nanmean(auc_enc);
    ace(s) = nanmean(auc_center_enc);
    ar(s) = nanmean(auc_rec);
    acr(s) = nanmean(auc_center_rec);
    
end

stats_enc = mes(ae', ace', 'hedgesg', 'isdep', 1);
stats_rec = mes(ar', acr', 'hedgesg', 'isdep', 1);
stats_evr = mes(ae', ar', 'hedgesg', 'isdep', 1);

% and generate a figure for supplement

figure;
set(gcf,'Position', [241   602   286   305]);

x = [1 2 4 5];
y = [nanmean(ae) nanmean(ace) nanmean(ar) nanmean(acr)];
e = [nanstd(ae) nanstd(ace) nanstd(ar) nanstd(acr)]/sqrt(length(ae));
y_all = [ae; ace; ar; acr]';

for p = 1:4
he = errorbar(x(p), y(p), e(p));
if p == 1 || p == 3
he.Color = 'k'; he.LineWidth = 2;
else
 he.Color = 'r'; he.LineWidth = 2;   
end
hold on;
end

hp = plot(x(1:2)' + .5*rand(size(y_all(:,1:2)')) - .25, y_all(:,1:2)', 'o-');
for p = 1:length(hp)
    hp(p).MarkerFaceColor = [.7 .7 .7];
    hp(p).MarkerEdgeColor = [.7 .7 .7];
    hp(p).Color = [.7 .7 .7];
    hp(p).MarkerSize = 2;
end

uistack(hp, 'bottom')

hp = plot(x(3:4)' + .5*rand(size(y_all(:,3:4)')) - .25, y_all(:,3:4)', 'o-');
for p = 1:length(hp)
    hp(p).MarkerFaceColor = [.7 .7 .7];
    hp(p).MarkerEdgeColor = [.7 .7 .7];
    hp(p).Color = [.7 .7 .7];
    hp(p).MarkerSize = 2;
end

uistack(hp, 'bottom')

set(gca, 'YLim', [0.5 1], ...
         'Xlim', [0 6], ...
         'box', 'off', ...
         'linewidth', 2, ...
         'XTick', [1.5 4.5], ...
         'XTickLabel', {'Study','Test'}, ...
         'FontSize', 12, ...
         'FontName', 'Arial');


xlabel('Task Phase');
ylabel('Classification Performance (AUC)');

% siglines

[h, p, c, st] = ttest(ae, ace);

if p < .001
    txt = '***';
elseif p < .01
    txt = '**';
elseif p < 0.05
    txt = '*';
elseif p < .1
    txt = '~';
else
    hl = []; ht = [];
end

if p < .1
yd = diff(get(gca,'YTick')); yd = yd(1);
ym = [ae ace]; ym = max(ym(:));
hl = plot(gca, x(1:2), [ym+.25*yd ym+.25*yd], 'k-');
hl.LineWidth = 2;

ht = text(gca, mean(x(1:2)), ym+.3*yd, txt, 'FontSize', 14);
ht.FontWeight = 'bold';
ht.HorizontalAlignment = 'center';
end

[h, p, c, st] = ttest(ar, acr);

if p < .001
    txt = '***';
elseif p < .01
    txt = '**';
elseif p < 0.05
    txt = '*';
elseif p < .1
    txt = '~';
else
    txt = '';
end

if p < .1
yd = diff(get(gca,'YTick')); yd = yd(1);
ym = [ar acr]; ym = max(ym(:));
hl = plot(gca, x(3:4), [ym+.25*yd ym+.25*yd], 'k-');
hl.LineWidth = 2;

ht = text(gca, mean(x(3:4)), ym+.3*yd, txt, 'FontSize', 14);
ht.FontWeight = 'bold';
ht.HorizontalAlignment = 'center';
end

tmp_h = get(gca,'Children');
hl = tmp_h(3:4);
hleg = legend(hl, 'Control','DGII');
hleg.Box = 'off'; hleg.Location = 'best';
